### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by XueWei** [AndreasPizsa/parse-decimal-number#14]
@AndreasPizsa I checked  license file, it's MIT license, and I can see the icon of MIT license. 
<img width="458" alt="screen shot 2017-08-21 at 2 51 14 pm" src="https://user-images.githubusercontent.com/137317/29539825-736ea4a2-8680-11e7-8f54-d0bc1e17ad98.png">

But in readme, the license part: Copyright (c) 2017 Andreas Pizsa (http://github.com/AndreasPizsa), contributors. 
Does this is typo? Or which license parse-decimal-number is? Please confirm.

**Comment by XueWei** [comment]
@AndreasPizsa Could you please take a look this?

**Comment by AndreasPizsa** [comment]
@XueWei this is actually standard (see [for example the NodeJS license](https://github.com/nodejs/node/blob/master/LICENSE)). The creator is the copyright holder who grants you a license, thus Copyright © <whoever> + MIT LICENSE.
