### ISSUE TITLE
Parse Decimal number without thousands delimiter

### ISSUE THREAD

**Issue by kirbyjs** [AndreasPizsa/parse-decimal-number#26]
### Current Behavior (US Number format)
1,234,123.12 parses correctly and returns number 1234123.12

### Expected Behavior
A option to turn the thousands delimiter off and have:
1,234,123.12 not be able to parse and return NaN.

**Comment by AndreasPizsa** [comment]
Thank you for opening this issue, @kirbyjs !

You can use an "invalid" thousands delimiter to get the behavior you want:

```js
parseDecimalNumber('1,234,123.12', [null, '.'])
// <- NaN

parseDecimalNumber('1234123.12', [null, '.'])
// <- 1234123.12

```


Does this solve your issue?

**Comment by kirbyjs** [comment]
@AndreasPizsa sorry I didn't clarify: 

I am currently using `cldr` with this module. I tried to set `group: undefined` but it [looks like](https://github.com/AndreasPizsa/parse-decimal-number/blob/master/dist/parse-decimal-number.js#L30) you default to the `inOpts.thousand` option if `inOpts.thousand` and `inOpts.group` is falsey. 

`cldr` doesn't have a `thousand` property so with the default options [here](https://github.com/AndreasPizsa/parse-decimal-number/blob/master/dist/parse-decimal-number.js#L59), `thousand` is still set to `,`. 

So I could also set `thousand: undefined` to get around the issue, but just wanted to check to see that that behavior is the expected behavior.

**Comment by AndreasPizsa** [comment]
Got it - that makes a lot of sense.

I'll look into it soon; meanwhile, if you want to submit a PR, please feel free to do so!

**Comment by AndreasPizsa** [comment]
Would this do what you're expecting, @kirbyjs ?

```
const cldr = require('cldr')
var parseDecimalNumber = require("parse-decimal-number")

const numberSymbols = cldr.extractNumberSymbols('en_US')
parseDecimalNumber("1234123.12", [null, numberSymbols.decimal])
// <- 1234123.12

parseDecimalNumber("1,234,123.12", [null, numberSymbols.decimal])
// <- NaN
```
https://runkit.com/andreaspizsa/runkit-npm-parse-decimal-number

**Comment by kirbyjs** [comment]
Yep, it works! I'm cool with that solution. Thanks a ton @AndreasPizsa!
